# Simple shell Makefile
inputFile = shell.c
outputFile = ysh
CC = gcc
CFLAGS = -Wall -g

all:
	$(CC) -o $(outputFile) $(CFLAGS) $(inputFile)
	ls --color
clean:
	rm -rf *.o $(outputFile)
	ls --color
test:
